image: Visual Studio 2017
init:
- git config --global core.autocrlf true
branches:
  only:
  - dev
  - /^release\/.*$/
  - /^(.*\/)?ci-.*$/
build_script:
- ps: .\run.ps1 -ci default-build
on_finish:
- ps: 7z a testlogs.zip testlogs
- ps: Push-AppveyorArtifact testlogs.zip
install:
- ps: Install-Product node 8
clone_depth: 1
environment:
  global:
    ASPNETCORE_TEST_LOG_DIR: $(APPVEYOR_BUILD_FOLDER)\testlogs
test: 'off'
deploy: 'off'
os: Visual Studio 2017
